# Generated by Django 5.0.4 on 2024-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('is_driver', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
    ]
