# Generated by Django 5.0.4 on 2024-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_ridepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmmPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.BooleanField()),
                ('post_every_minute', models.IntegerField()),
                ('photo', models.ImageField(upload_to='smm/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
