# Generated by Django 5.0.4 on 2024-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0009_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
