# Generated by Django 5.0.4 on 2024-05-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0010_botuser_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridepost',
            old_name='user',
            new_name='ordered_by',
        ),
        migrations.AddField(
            model_name='ridepost',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to='telegram_app.botuser'),
        ),
    ]
