# Generated by Django 5.0.4 on 2024-05-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0011_rename_user_ridepost_ordered_by_ridepost_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepost',
            name='posted_on_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_on_group', to='telegram_app.telegramgroup'),
        ),
    ]
