# Generated by Django 5.0.4 on 2024-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0012_ridepost_posted_on_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepost',
            name='group_message_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
