# Generated by Django 5.0.4 on 2024-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0013_ridepost_group_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepost',
            name='last_ride_message_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
