# Generated by Django 5.0.4 on 2024-05-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0016_botuser_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('translated_name', models.CharField(max_length=200)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='telegram_app.road')),
            ],
        ),
    ]
